import React, { useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import ServiceRegistry from './components/ServiceRegistry';
import './App.css';

const INCIDENTS_API = `${process.env.REACT_APP_API_BASE_URL || ''}/api/incidents`;
const SERVICES_API = '/api/services';
const SOCKET_URL = process.env.REACT_APP_WS_URL || window.location.origin;
const STATUSES = ['Open', 'In Progress', 'Resolved'];

const formatDate = (value) => value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Not available';
const formatTime = (value) => value ? new Date(value).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '--:--';

function StatusBadge({ status }) {
  return <span className={`status-badge status-${status.toLowerCase().replace(' ', '-')}`}><i />{status}</span>;
}

function EmptyState({ title, detail }) {
  return <div className="empty-state"><span className="empty-mark">✓</span><strong>{title}</strong><p>{detail}</p></div>;
}

function IncidentCard({ incident, onSelect, onStartAgent }) {
  return <article className="incident-card" onClick={() => onSelect(incident)}>
    <div className="card-topline"><span className={`severity severity-${incident.severity.toLowerCase()}`}>{incident.severity}</span><span className="incident-id">#{incident._id.slice(-6).toUpperCase()}</span></div>
    <h3>{incident.title}</h3><p>{incident.description || 'No description provided.'}</p>
    <div className="card-meta"><StatusBadge status={incident.status} /><span>{incident.raisedBy || 'Legacy record'}</span><time>{formatDate(incident.createdAt)}</time></div>
    {incident.agentState === 'analyzing' && <div className="agent-running"><i /> Agent is working live</div>}
    {incident.agentState !== 'analyzing' && incident.status !== 'Resolved' && <button className="card-agent-action" onClick={(event) => { event.stopPropagation(); onStartAgent(incident._id); }}>Run agent <b>→</b></button>}
  </article>;
}

function Activity({ activities }) {
  if (!activities.length) return <EmptyState title="No activity yet" detail="Incident and agent events will appear here in real time." />;
  return <div className="activity-feed">{activities.map((activity, index) => <div className="activity-item" key={`${activity.id}-${activity.event}-${index}`}><span className="activity-dot" /><div><strong>{activity.event}</strong><p>{activity.title}</p><small>{activity.detail || 'System event'} · {formatTime(activity.createdAt)}</small></div></div>)}</div>;
}

function Timeline({ incident }) {
  if (!incident.timeline?.length) return <EmptyState title="Timeline will appear here" detail="Events are recorded as the incident moves through its lifecycle." />;
  return <div className="timeline">{incident.timeline.map((entry, index) => <div className="timeline-item" key={`${entry.event}-${index}`}><span className="timeline-dot" /><div><time>{formatTime(entry.createdAt)}</time><strong>{entry.event}</strong><p>{entry.detail}</p><small>{entry.actor || 'system'}</small></div></div>)}</div>;
}

function AgentPanel({ incident, onStartAgent, question, setQuestion, answer, ask }) {
  if (!incident) return <div className="agent-panel empty-agent"><span className="agent-glyph">AI</span><p className="kicker">CORTEX AGENT</p><h2>Ready to investigate</h2><p>Select an active incident to focus the agent context.</p></div>;
  return <div className="agent-panel"><div className="agent-heading"><span className="agent-glyph">AI</span><div><p className="kicker">CORTEX AGENT</p><h2>{incident.agentState === 'analyzing' ? 'Working on incident' : 'Investigation ready'}</h2></div><span className={`agent-state ${incident.agentState}`}>{incident.agentState === 'analyzing' ? '● LIVE' : 'IDLE'}</span></div><div className="agent-context"><span>Current context</span><strong>{incident.title}</strong><small>{incident.severity} severity · {incident.status}</small></div><div className="agent-progress"><p className="kicker">INVESTIGATION PROGRESS</p>{(incident.agentActivity || []).map((step) => <div className="agent-step" key={step.step}><b>✓</b><span>{step.step}</span><time>{formatTime(step.createdAt)}</time></div>)}{incident.agentState === 'analyzing' && <div className="agent-step is-running"><b>→</b><span>Working on next signal</span><time>now</time></div>}</div>{incident.rootCause && <div className="agent-insight"><span>ANALYZED</span><p>{incident.rootCause}</p></div>}{incident.resolution && <div className="agent-insight recommendation"><span>RECOMMENDED</span><p>{incident.resolution}</p></div>}<form className="agent-question" onSubmit={ask}><input aria-label="Ask about this incident" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about this incident..." /><button type="submit">Ask</button></form>{answer && <p className="agent-answer">{answer}</p>}<button className="agent-button" onClick={() => onStartAgent(incident._id)} disabled={incident.agentState === 'analyzing'}>{incident.agentState === 'analyzing' ? 'Agent is working...' : 'Start investigation'} <b>→</b></button></div>;
}

function IncidentList({ incidents, query, setQuery, statusFilter, setStatusFilter, onSelect, onStartAgent, emptyTitle, emptyDetail }) {
  return <section className="list-page"><div className="list-toolbar"><div className="search-bar"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search incidents..." /></div><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>All</option>{STATUSES.map((status) => <option key={status}>{status}</option>)}</select></div>{incidents.length ? <div className="incident-list">{incidents.map((incident) => <IncidentCard key={incident._id} incident={incident} onSelect={onSelect} onStartAgent={onStartAgent} />)}</div> : <EmptyState title={emptyTitle} detail={emptyDetail} />}</section>;
}

function CreatePanel({ form, update, submit }) {
  return <section className="create-panel panel"><div className="panel-title"><div><p className="kicker">NEW EVENT</p><h3>Report an incident</h3></div><span>Required fields marked <b className="required-mark">*</b></span></div><form className="create-form" onSubmit={submit}><label>Incident title <b className="required-mark">*</b><input name="title" value={form.title} onChange={update} placeholder="What is happening?" required /></label><label>Raised by <b className="required-mark">*</b><input name="raisedBy" value={form.raisedBy} onChange={update} placeholder="Operator name" required /></label><label>Description<textarea name="description" value={form.description} onChange={update} placeholder="Impact, scope, and symptoms" /></label><label>Knowledge-base note<textarea name="knowledgeBase" value={form.knowledgeBase} onChange={update} placeholder="Relevant runbook or fix" /></label><label>Severity <b className="required-mark">*</b><select name="severity" value={form.severity} onChange={update}><option>Low</option><option>Medium</option><option>High</option></select></label><button className="primary-button" type="submit">Create incident <b>→</b></button></form></section>;
}

function App() {
  const [incidents, setIncidents] = useState([]);
  const [services, setServices] = useState([]);
  const [view, setView] = useState('overview');
  const [selectedId, setSelectedId] = useState(null);
  const [query, setQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [loading, setLoading] = useState(true);
  const [connected, setConnected] = useState(false);
  const [error, setError] = useState('');
  const [agentQuestion, setAgentQuestion] = useState('');
  const [agentAnswer, setAgentAnswer] = useState('');
  const [form, setForm] = useState({ title: '', raisedBy: '', description: '', severity: 'Low', knowledgeBase: '' });

  const loadIncidents = async () => { try { setLoading(true); const response = await fetch(INCIDENTS_API); if (!response.ok) throw new Error(); setIncidents(await response.json()); setError(''); } catch (err) { setError('Unable to load incidents. Check the API connection and retry.'); } finally { setLoading(false); } };
  const loadServices = async () => { try { const response = await fetch(SERVICES_API); if (!response.ok) throw new Error(); setServices(await response.json()); } catch (err) { setError('Unable to load service registry.'); } };
  useEffect(() => { loadIncidents(); loadServices(); }, []);
  useEffect(() => { const socket = io(SOCKET_URL, { transports: ['websocket', 'polling'] }); socket.on('connect', () => setConnected(true)); socket.on('disconnect', () => setConnected(false)); socket.on('incident:created', (item) => setIncidents((current) => [item, ...current.filter((entry) => entry._id !== item._id)])); socket.on('incident:updated', (item) => setIncidents((current) => current.map((entry) => entry._id === item._id ? item : entry))); socket.on('agent:started', (item) => setIncidents((current) => current.map((entry) => entry._id === item._id ? item : entry))); socket.on('agent:progress', (item) => setIncidents((current) => current.map((entry) => entry._id === item._id ? item : entry))); socket.on('incident:deleted', ({ id }) => setIncidents((current) => current.filter((entry) => entry._id !== id))); socket.on('service:created', (item) => setServices((current) => [...current.filter((entry) => entry._id !== item._id), item].sort((a, b) => a.name.localeCompare(b.name)))); socket.on('service:updated', (item) => setServices((current) => current.map((entry) => entry._id === item._id ? item : entry))); socket.on('service:deleted', ({ id }) => setServices((current) => current.filter((entry) => entry._id !== id))); return () => socket.disconnect(); }, []);

  const selected = incidents.find((incident) => incident._id === selectedId) || null;
  const active = incidents.filter((incident) => incident.status !== 'Resolved');
  const resolved = incidents.filter((incident) => incident.status === 'Resolved');
  const filtered = useMemo(() => incidents.filter((incident) => { const text = `${incident.title} ${incident.description || ''} ${incident.knowledgeBase || ''}`.toLowerCase(); return (statusFilter === 'All' || incident.status === statusFilter) && text.includes(query.toLowerCase()); }), [incidents, query, statusFilter]);
  const activities = incidents.flatMap((incident) => (incident.timeline || []).map((entry) => ({ ...entry, title: incident.title, id: incident._id }))).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 12);
  const highCount = active.filter((incident) => incident.severity === 'High').length;
  const investigateCount = active.filter((incident) => incident.agentState === 'analyzing' || incident.status === 'In Progress').length;
  const navigate = (next) => { setView(next); setSelectedId(null); setQuery(''); setStatusFilter('All'); };
  const selectIncident = (incident) => { setSelectedId(incident._id); setView('detail'); };
  const updateForm = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const createIncident = async (event) => { event.preventDefault(); try { const response = await fetch(INCIDENTS_API, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(); setForm({ title: '', raisedBy: '', description: '', severity: 'Low', knowledgeBase: '' }); } catch (err) { setError('Unable to create incident. Please retry.'); } };
  const startAgent = async (id) => { setSelectedId(id); try { const response = await fetch(`${INCIDENTS_API}/${id}/agent/start`, { method: 'POST' }); if (!response.ok) throw new Error(); } catch (err) { setError('Unable to start the agent. Please retry.'); } };
  const askAgent = (event) => { event.preventDefault(); const target = selected || active[0]; if (!target) return setAgentAnswer('Create an incident first so I have operational context.'); const question = agentQuestion.toLowerCase(); if (question.includes('root') || question.includes('cause')) setAgentAnswer(target.rootCause || 'No root cause has been recorded yet. Start the investigation to collect evidence.'); else if (question.includes('knowledge') || question.includes('runbook') || question.includes('similar')) setAgentAnswer(target.knowledgeBase || 'No incident-specific knowledge note is attached yet.'); else if (question.includes('next') || question.includes('check')) setAgentAnswer(target.agentState === 'analyzing' ? 'The agent is checking service health, incident signals, and knowledge context.' : 'Start the agent, assess impact and scope, and record the next verified action.'); else setAgentAnswer(`${target.title} is ${target.status.toLowerCase()} with ${target.severity.toLowerCase()} severity.`); };
  const createService = async (service) => { const response = await fetch(SERVICES_API, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(service) }); if (!response.ok) throw new Error((await response.json()).error || 'Service creation failed'); };
  const updateService = async (id, service) => { const response = await fetch(`${SERVICES_API}/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(service) }); if (!response.ok) throw new Error((await response.json()).error || 'Service update failed'); };
  const deleteService = async (id) => { const response = await fetch(`${SERVICES_API}/${id}`, { method: 'DELETE' }); if (!response.ok) throw new Error('Service deletion failed'); };

  const pageTitle = { overview: 'Good evening', active: 'Active incidents', resolved: 'Resolved incidents', activity: 'Live activity', agent: 'Agent workspace', knowledge: 'Knowledge base', services: 'Service registry', settings: 'System settings' }[view] || 'CortexOps';
  const pageSubtitle = { overview: 'Infrastructure overview and incident status.', active: `${active.length} incidents currently need attention.`, resolved: `${resolved.length} incidents in historical archive.`, services: `${services.length} services registered for monitoring.` }[view] || 'Follow the operational record from detection to resolution.';
  const renderDetail = () => selected ? <main className="content detail-page"><button className="back-button" onClick={() => navigate('active')}>← Back to incidents</button><div className="detail-header"><div><p className="kicker">INCIDENT #{selected._id.slice(-6).toUpperCase()}</p><h2>{selected.title}</h2><p>{selected.description || 'No description provided.'}</p></div><div className="detail-badges"><span className={`severity severity-${selected.severity.toLowerCase()}`}>{selected.severity}</span><StatusBadge status={selected.status} /></div></div><div className="detail-context"><span>Raised by <b>{selected.raisedBy || 'Legacy record'}</b></span><span>Created <b>{formatDate(selected.createdAt)}</b></span><span>Resolved <b>{formatDate(selected.resolvedAt)}</b></span></div><div className="detail-grid"><section className="detail-card"><div className="panel-title"><div><p className="kicker">INCIDENT TIMELINE</p><h3>Operational history</h3></div></div><Timeline incident={selected} /></section><AgentPanel incident={selected} onStartAgent={startAgent} question={agentQuestion} setQuestion={setAgentQuestion} answer={agentAnswer} ask={askAgent} /></div><section className="detail-card knowledge-detail-card"><div className="panel-title"><div><p className="kicker">KNOWLEDGE BASE</p><h3>Incident context</h3></div></div><p>{selected.knowledgeBase || 'No incident-specific knowledge note is attached yet.'}</p></section></main> : <main className="content"><EmptyState title="Select an incident" detail="Choose an incident from the queue to open its command center." /></main>;
  const renderOverview = () => loading ? <div className="loading-state">Loading current operational data...</div> : <><section className="metrics"><Metric label="Active" value={active.length} detail="Current queue" tone="orange" /><Metric label="Critical / high" value={highCount} detail="Needs attention" tone="red" /><Metric label="Investigating" value={investigateCount} detail="Agent or operator" tone="blue" /><Metric label="Resolved" value={resolved.length} detail="Historical archive" tone="green" /></section><div className="overview-grid"><section className="panel"><div className="panel-title"><div><p className="kicker">OPERATIONS</p><h3>Active incidents</h3></div><span>{active.length} open</span></div>{active.length ? <div className="compact-list">{active.slice(0, 5).map((incident) => <IncidentCard key={incident._id} incident={incident} onSelect={selectIncident} onStartAgent={startAgent} />)}</div> : <EmptyState title="No active incidents" detail="All monitored systems are currently operating normally." />}</section><section className="panel health-panel"><div className="panel-title"><div><p className="kicker">SIGNALS</p><h3>Service health</h3></div><span className="healthy-label"><i /> Connected</span></div>{services.slice(0, 4).map((service) => <div className="health-row" key={service._id}><span className="health-icon">SV</span><div><strong>{service.name}</strong><small>{service.environment} · {service.owner}</small></div><b>{service.status}</b></div>)}{!services.length && <EmptyState title="No services registered" detail="Register services to prepare health monitoring." />}</section></div><section className="panel activity-panel"><div className="panel-title"><div><p className="kicker">EVENT STREAM</p><h3>Live activity</h3></div></div><Activity activities={activities.slice(0, 5)} /></section><CreatePanel form={form} update={updateForm} submit={createIncident} /></>;
  const renderMain = () => { if (view === 'detail') return renderDetail(); return <main className="content"><div className="page-heading"><div><p className="kicker">{connected ? '● LIVE SYSTEM' : '○ CONNECTING'}</p><h2>{pageTitle}</h2><p>{pageSubtitle}</p></div>{view !== 'settings' && view !== 'services' && <button className="primary-button" onClick={() => document.querySelector('.create-panel')?.scrollIntoView({ behavior: 'smooth' })}>+ Report incident</button>}</div>{error && <div className="error-banner"><strong>Unable to complete action</strong><span>{error}</span><button onClick={() => { setError(''); loadIncidents(); loadServices(); }}>Retry</button></div>}{view === 'overview' && renderOverview()}{view === 'active' && <IncidentList incidents={filtered.filter((incident) => incident.status !== 'Resolved')} query={query} setQuery={setQuery} statusFilter={statusFilter} setStatusFilter={setStatusFilter} onSelect={selectIncident} onStartAgent={startAgent} emptyTitle="No active incidents" emptyDetail="All monitored incidents are currently resolved." />}{view === 'resolved' && <IncidentList incidents={filtered.filter((incident) => incident.status === 'Resolved')} query={query} setQuery={setQuery} statusFilter={statusFilter} setStatusFilter={setStatusFilter} onSelect={selectIncident} onStartAgent={startAgent} emptyTitle="No resolved incidents" emptyDetail="Resolved incidents remain available with their complete history." />}{view === 'activity' && <section className="panel"><Activity activities={activities} /></section>}{view === 'agent' && <div className="agent-workspace"><AgentPanel incident={selected || active[0]} onStartAgent={startAgent} question={agentQuestion} setQuestion={setAgentQuestion} answer={agentAnswer} ask={askAgent} /><section className="panel"><Activity activities={activities} /></section></div>}{view === 'knowledge' && <section className="panel"><div className="search-bar"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search incident knowledge..." /></div><div className="knowledge-list">{filtered.filter((incident) => incident.knowledgeBase).map((incident) => <div className="knowledge-row" key={incident._id}><span className="knowledge-icon">KB</span><span><strong>{incident.title}</strong><small>{incident.knowledgeBase}</small></span></div>)}</div></section>}{view === 'services' && <ServiceRegistry services={services} onCreate={createService} onUpdate={updateService} onDelete={deleteService} />}{view === 'settings' && <Settings connected={connected} />}</main>; };

  return <div className="app-shell"><aside className={`sidebar ${sidebarOpen ? '' : 'collapsed'}`}><div className="side-brand"><span>CO</span>{sidebarOpen && <strong>CORTEX<span>OPS</span></strong>}</div><nav><NavGroup label="Workspace" expanded={sidebarOpen} view={view} navigate={navigate} items={[['overview', 'Overview', '⌂'], ['active', 'Active incidents', '◉', active.length], ['resolved', 'Resolved archive', '✓', resolved.length], ['services', 'Services', '▦', services.length]]} /><NavGroup label="Intelligence" expanded={sidebarOpen} view={view} navigate={navigate} items={[['agent', 'Agent workspace', '✦'], ['knowledge', 'Knowledge base', '▤']]} /><NavGroup label="System" expanded={sidebarOpen} view={view} navigate={navigate} items={[['activity', 'Activity', '≡'], ['settings', 'Settings', '⚙']]} /></nav><div className="side-footer">{sidebarOpen && <><span className="avatar">KP</span><div><strong>Operator</strong><small>Production workspace</small></div></>}</div></aside><div className="app-main"><header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(!sidebarOpen)}>☰</button><div className="global-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search incidents, services, knowledge..." /><kbd>⌘ K</kbd></div><div className="top-actions"><span className={`connection ${connected ? 'connected' : ''}`}><i />{connected ? 'Live' : 'Connecting'}</span><button className="icon-button" title="Critical incident count">♢<b>{highCount || ''}</b></button><span className="top-avatar">KP</span></div></header>{renderMain()}</div></div>;
}
function NavGroup({ label, items, view, navigate, expanded }) { return <div className="nav-group"><span className="nav-label">{expanded ? label : '·'}</span>{items.map(([id, name, icon, count]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => navigate(id)} title={name}><span>{icon}</span>{expanded && <>{name}{count > 0 && <b>{count}</b>}</>}</button>)}</div>; }
function Metric({ label, value, detail, tone }) { return <div className={`metric metric-${tone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function Settings({ connected }) { return <section className="settings-panel panel"><p className="kicker">SYSTEM</p><h3>Workspace settings</h3><div className="setting-row"><span>Realtime connection</span><strong>{connected ? 'Connected' : 'Connecting'}</strong></div><div className="setting-row"><span>Data source</span><strong>MongoDB Atlas</strong></div><p className="settings-note">CortexOps uses persisted incidents, Socket.IO events, and the Service Registry. No mock service data is displayed.</p></section>; }
export default App;
